# Generated by Django 3.2.5 on 2021-08-17 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialnumber', models.CharField(max_length=12, unique=True)),
                ('model', models.CharField(blank=True, max_length=12)),
                ('batterylife', models.IntegerField(blank=True)),
                ('capacity', models.IntegerField(blank=True)),
                ('status', models.BooleanField(blank=True, default=True)),
                ('removed_from_DEP', models.BooleanField(blank=True, default=False)),
                ('status_defect', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
