# Generated by Django 3.2.5 on 2021-07-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialnumber', models.CharField(max_length=12, unique=True)),
                ('model', models.CharField(max_length=12, unique=True)),
                ('batterylife', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('color', models.CharField(max_length=30)),
                ('status', models.BooleanField()),
            ],
        ),
    ]
