# Generated by Django 3.2.5 on 2021-09-01 09:46

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialnumber', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 4', regex='^.{12}$')])),
                ('model', models.CharField(blank=True, max_length=12)),
                ('batterylife', models.IntegerField(blank=True, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, default=True)),
                ('removed_from_DEP', models.BooleanField(default=False)),
                ('status_defect', models.BooleanField(default=False)),
                ('qrcode', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Handout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('is_shipped', models.BooleanField(default=False)),
                ('owner', models.CharField(default='system', max_length=20)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
