# Generated by Django 3.2.5 on 2021-08-17 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='batterylife',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='removed_from_DEP',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='status_defect',
            field=models.BooleanField(default=False),
        ),
    ]
