# Generated by Django 3.2.5 on 2021-08-24 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handout',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
