# Generated by Django 3.2.8 on 2021-12-03 13:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='serialnumber',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 12', regex='^.{12}$')]),
        ),
    ]
