# Generated by Django 3.2.8 on 2021-12-12 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_device_serialnumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='status_defect',
            new_name='condition',
        ),
    ]
